sudo: required
language: java

env:
  global:
    - "MYSQL_DATABASE=irida_integration_test"
    - "MYSQL_USER=test"
    - "MYSQL_PASSWORD=test"
    - "DB_MAX_WAIT_MILLIS=30000"

services:
  - docker
  - mysql

dist: xenial

jdk:
  - openjdk8

rvm:
  - 2.4.1

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get install libgconf-2-4

install:
  - mysql -e "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'; GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USER'@'localhost';"
  - mvn -version
  - pushd lib; ./install-libs.sh; popd
  - gem install jekyll
  - gem install pygments.rb

stages:
  - prepare
  - test

jobs:
  include:
    - stage: prepare
      script: ./run-tests.sh docker_cache
    - stage: test
      script: ./run-tests.sh galaxy_testing
    - stage: test
      script: ./run-tests.sh galaxy_pipeline_teting
    - stage: test
      script: ./run-tests.sh ui_testing
    - stage: test
      script: ./run-tests.sh doc_testing
    - stage: test
      script: ./run-tests.sh service_testing
    - stage: test
      script: ./run-tests.sh rest_testing
