name: Maven test

on:
  push:
    branches: [ actions-test ]

jobs:
  integration-test:
    env:
      DATABASE_PORT: 3800

    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        suite: ['service_testing', 'rest_testing', 'ui_testing', 'doc_testing', 'galaxy_testing', 'galaxy_pipeline_testing']

    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    #- name: Start database
    #  run: sudo /etc/init.d/mysql start
    - name: 'Database setup'
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: ${{ env.DATABASE_PORT }}
        container port: ${{ env.DATABASE_PORT }}
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '5.7'
        mysql database: 'irida_integration_test'
        mysql user: 'test'
        mysql password: 'test'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install libraries
      run: pushd lib; ./install-libs.sh; popd; sudo gem install jekyll; sudo gem install pygments.rb
    - name: Build with Maven
      run: ./run-tests.sh --db-port ${{ env.DATABASE_PORT }} ${{ matrix.suite }}

