name: Maven test

on:
  pull_request: null

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'irida_integration_test'
        mysql user: 'test'
        mysql password: 'test'
    - name: Service build
      run: | 
        sudo apt-get install libgconf-2-4
        ./run-tests.sh service_testing

