name: Maven test

on:
  push:
    branches: [ actions-test ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['service_testing', 'rest_testing', 'doc_testing']

    steps:
    - uses: actions/checkout@v2
    - name: Start database
      run: sudo /etc/init.d/mysql start
    - name: 'Database setup'
      run: mysql -uroot -proot -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test'; GRANT ALL ON irida_integration_test.* to 'test'@'localhost';"
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install libraries
      run: pushd lib; ./install-libs.sh; popd; gem install jekyll; gem install pygments.rb
    - name: Build with Maven
      run: ./run-tests.sh ${{ matrix.suite }}

