name: Maven IT

on: 
  pull_request: null

jobs:
  build:
    runs-on: ubuntu-latest
      
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mvn -version
#       - run: pushd lib; ./install-libs.sh; popd
#       - run: gem install jekyll
#       - run: gem install pygments.rb
#       - run: mvn site

